name: dart_quill
description: A web app that uses AngularDart
version: 1.0.0
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  
  # quill_delta:
  #   git:
  #     url: https://github.com/pulyaevskiy/quill-delta-dart.git
  #     ref: master
  ngdart: ^8.0.0-dev.4
  ngforms: any
  ngrouter: any

  #collection: ^1.17.0
  diff_match_patch: ^0.4.1
  quiver: ^3.2.1
  collection: ^1.18.0  
  equatable: ^2.0.7
  meta: ^1.15.0
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  test: ^1.24.0